---

- name: Gather openjdk download info
  when: openjdk_artifact is undefined and not openjdk_version_8
  block:
    - name: Gather openjdk download url
      ansible.builtin.set_fact:
        _openjdk_download_url:  >-
          {{ lookup("template", "download_url.j2") | trim }}

    - name: Parse openjdk download info
      ansible.builtin.set_fact:
        _openjdk_download_host: >-
          https://{{ _openjdk_download_url | urlsplit("hostname") }}
        _openjdk_download_path: >-
          {{ _openjdk_download_url | urlsplit("path") | dirname }}
        _openjdk_download_file: >-
          {{ _openjdk_download_url | urlsplit("path") | basename }}

- name: Set fact with JAVA_HOME pointing to operating system package
  ansible.builtin.set_fact:
    openjdk_java_home: /usr/lib/jvm/java-1.8.0-openjdk
  when: openjdk_version_8

- name: Setup Set fact with openjdk effective version
  ansible.builtin.set_fact:
    openjdk_effective_version: >-
      {{ lookup("template", "effective_version.j2") | trim }}

- name: Prepare openjdk artifact
  when: openjdk_artifact is undefined
  block:
    - name: Assert version to download is valid
      ansible.builtin.assert:
        that: openjdk_version_8 or openjdk_check_version_exists

    - name: Setup default artifact
      ansible.builtin.set_fact:
        openjdk_default_artifact:
          id: openjdk_bins
          type: https
          host: "{{ _openjdk_download_host }}"
          path: "{{ _openjdk_download_path }}"
          file: "{{ _openjdk_download_file }}"
          dest: /opt
          timeout: 120
          validate_certs: yes
      when: not openjdk_version_8

    - name: Set fact with JAVA_HOME pointing to default artifact
      ansible.builtin.set_fact:
        openjdk_java_home: >-
          {{ openjdk_default_artifact.dest
             ~ "/jdk-"
             ~ openjdk_effective_version }}
      when: not openjdk_version_8 and openjdk_artifact is not defined

- name: Set fact with JAVA_HOME pointing to artifact defined
  ansible.builtin.set_fact:
    openjdk_java_home: >-
      {{ openjdk_artifact.dest }}/jdk-{{ openjdk_artifact_version }}
  when: not openjdk_version_8 and openjdk_artifact is defined
  vars:
    openjdk_artifact_version: >-
      {{ openjdk_artifact.file.split('-')[1].split('_')[0] }}

- name: Check if openjdk version is already deployed
  ansible.builtin.stat:
    path: "{{ openjdk_java_home }}"
  register: openjdk_check_installed_result
