---

- name: Set fact with JAVA_HOME pointing to operating system package
  set_fact:
    openjdk_java_home: /usr/lib/jvm/jre-1.8.0-openjdk
  when: openjdk_version_8

- when: openjdk_artifact is undefined
  block:
    - name: Assert version to download is valid
      assert:
        that: openjdk_version_8 or openjdk_check_version_exists

    - name: Setup default artifact
      set_fact:
        openjdk_default_artifact:
          id: openjdk_bins
          type: https
          host: "{{ openjdk_download_host }}"
          path: "{{ openjdk_download_path }}"
          file: "{{ openjdk_download_file }}"
          dest: /opt
          timeout: 120
          validate_certs: yes
      when: not openjdk_version_8

    - name: Set fact with JAVA_HOME pointing to default artifact
      set_fact:
        openjdk_java_home: >-
          {{ openjdk_default_artifact.dest
             ~ "/jdk-"
             ~ openjdk_effective_version }}
      when: not openjdk_version_8 and openjdk_artifact is not defined

- name: Set fact with JAVA_HOME pointing to artifact defined
  set_fact:
    openjdk_java_home: >-
      {{ openjdk_artifact.dest }}/jdk-{{ openjdk_artifact_version }}
  when: not openjdk_version_8 and openjdk_artifact is defined
  vars:
    openjdk_artifact_version: >-
      {{ openjdk_artifact.file.split('-')[1].split('_')[0] }}

- name: Check if OpenJDK version is already deployed
  stat:
    path: "{{ openjdk_java_home }}"
  register: openjdk_check_installed_result
