---

- name: Configure openjdk
  block:
    - name: Setup alternatives to openjdk java
      alternatives:
        name: "{{ item }}"
        link: "/usr/bin/{{ item }}"
        path: "{{ openjdk_java_home }}/bin/{{ item }}"
      loop: "{{ openjdk_alternatives }}"
      loop_control:
        label: "{{ item }}"
      when:
        - openjdk_state == "present"
        - openjdk_update_alternatives | bool

    - name: Remove symlinks created by alternatives module
      ansible.builtin.file:
        path: "/usr/bin/{{ item }}"
        state: absent
      loop: "{{ openjdk_alternatives }}"
      loop_control:
        label: "{{ item }}"
      when:
        - openjdk_state == "absent"
        - openjdk_update_alternatives | bool

    - name: Check kesytore
      ansible.builtin.stat:
        path: "{{ openjdk_java_home }}/lib/security/cacerts"
      register: openjdk_java_keystore_result

    - name: Configure openjdk keystore
      block:
        - name: Remove factory keystore
          ansible.builtin.file:
            path: "{{ openjdk_java_home }}/lib/security/cacerts"
            state: absent

        - name: Setup system wide keystore
          ansible.builtin.file:
            src: /etc/pki/java/cacerts
            dest: "{{ openjdk_java_home }}/lib/security/cacerts"
            state: link
      when: not openjdk_java_keystore_result.stat.islnk
  when: not openjdk_version_8
