---

- name: Download and unarchive OpenJDK binaries
  include_role:
    name: amtega.artifact
  when: openjdk_state == 'present'
  vars:
    override:
      download: "{{ not openjdk_check_installed_result.stat.exists }}"
      unarchive: yes
      unarchive_remove: yes
      force: yes
      no_log: no
    artifact: >-
      {{ openjdk_artifact
         | default(openjdk_default_artifact)
         | default({})
         | combine(override) }}
