---

- name: Setup openjdk
  block:
    - ansible.builtin.include_tasks: check.yml

    - ansible.builtin.include_tasks: install.yml
      when: openjdk_state == "present"

    - ansible.builtin.include_tasks: configure.yml

    - ansible.builtin.include_tasks: uninstall.yml
      when: openjdk_state == "absent"
  tags:
    - role::openjdk
