---

# Role tasks

- block:
    - include_tasks: check.yml

    - include_tasks: install.yml
      when: openjdk_state == "present"
      
    - include_tasks: configure.yml

    - include_tasks: uninstall.yml
      when: openjdk_state == "absent"
  tags:
    - role::openjdk
