---

- block:
    - name: Remove openjdk from system
      file:
        path: "{{ openjdk_java_home }}"
        state: absent

    - name: Remove openjdk artifact facts
      include_role:
        name: amtega.artifact
      vars:
        override:
          state: absent
        artifact: >-
          {{ openjdk_artifact
             | default(openjdk_default_artifact)
             | combine(override) }}

  when: openjdk_state == 'absent'
