---

- name: Uninstall openjdk artifact
  block:
    - name: Remove openjdk from system
      ansible.builtin.file:
        path: "{{ openjdk_java_home }}"
        state: absent

    - name: Remove openjdk artifact facts
      ansible.builtin.include_role:
        name: amtega.artifact
      vars:
        override:
          state: absent
        artifact: >-
          {{ openjdk_artifact
             | default(openjdk_default_artifact)
             | combine(override) }}
  when: not openjdk_version_8

- name: Uninstall openjdk operating system package
  block:
    - name: Uninstall operating system package
      ansible.builtin.include_role:
        name: amtega.packages
      vars:
        packages_os:
          all:
            all:
              java-1.8.0-openjdk-headless: absent
  when: openjdk_version_8
