---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Gather java version
      ansible.builtin.command: /usr/bin/java -version
      changed_when: no
      register: check_openjdk_result

    - name: Assert openjdk is installed
      ansible.builtin.assert:
        that: >-
          check_openjdk_result.stdout
          ~ check_openjdk_result.stderr is search("openjdk Runtime Environment")

    - name: Assert openjdk version is valid
      ansible.builtin.assert:
        that: >-
          check_openjdk_result.stdout
          ~ check_openjdk_result.stderr is search("build " ~ openjdk_version)
      when: openjdk_version is defined and openjdk_version != "latest"
